SELECT 
	sys.index_columns.[object_id],
	sys.index_columns.[index_id],
	sys.index_columns.[index_column_id],
	sys.index_columns.[column_id],
	sys.index_columns.[key_ordinal],
	sys.index_columns.[is_descending_key]
FROM 
	sys.index_columns